  # Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    #build an environment
    pre-install:
      - export CUSTOM_ENV_DIR= /docs/build/
      - mkdir -p $CUSTOM_ENV_DIR
      - conda env create -p $CUSTOM_ENV_DIR -f docs/source/environment.yml
      - export READTHEDOCS_VIRTUALENV_PATH=$CUSTOM_ENV_DIR
    post_install:
      # Run the build commands within the specified environment
      - conda run -p $READTHEDOCS_VIRTUALENV_PATH sphinx-build -M html docs/source/ docs/build/

python:
  install:
    - method: pip
      path: .

conda:
  environment: docs/source/environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
