name: mesa_geo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlite_sphinx
  - xeus-python
  - pip>=20.1
  - pip:
      - geopandas
      - numpy
      - sphinx
      - sphinx_rtd_theme
      - myst-nb
      - mesa~=2.3.0
      - xyzservices>=2022.9.0
      - jupyter_bridge
      - libpysal
      - rtree
      - rasterio
      - shapely
      - pyproj
      - folium
      - ipyleaflet

