name: mesa_geo
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python==3.10
  - xeus-python
  - pip>=20.1
  - pip:
      - mesa~=2.3.0
      - xyzservices>=2022.9.0
      - jupyter_bridge==0.3.5
      - jupyterlite_sphinx==0.15.0
      - myst_nb==1.1.0
      - myst_parser==3.0.1
      - geopandas==0.14.4
      - ipyleaflet==0.19.1
