name: mesa_geo
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip>=20.1
  - pip:
      - mesa~=2.3.0
      - xyzservices>=2022.9.0
      - jupyter_bridge==0.3.5
      - jupyterlite_sphinx==0.15.0
      - myst_nb==1.1.0
      - geopandas==0.14.4
      - ipyleaflet==0.19.1

