name: mesa_geo
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - geopandas~=0.14.4
  - ipyleaflet~=0.19.1
  - pip>=20.1
  - pip:
      - mesa~=2.3.0
      - xyzservices>=2022.9.0
      - jupyter_bridge==0.3.5

