name: mesa_geo
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - geopandas
  - numpy
  - sphinx
  - sphinx_rtd_theme
  - libpysal
  - rtree
  - rasterio
  - shapely
  - pyproj
  - folium
  - ipyleaflet
  - pip>=20.1
  - pip:
      - mesa~=2.3.0
      - xeus-python
      - myst-nb
      - jupyterlite_sphinx
      - xyzservices>=2022.9.0
      - jupyter_bridge

