name: build

on:
  push:
    branches:
    - main
    - release**
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: codespell-project/actions-codespell@master
      with:
        ignore_words_file: .codespellignore
        skip: .*bootstrap.*,*.js,.*bootstrap-theme.css.map