name: Release
on:
  push:
    tags:
    - "v*"
    branches:
    - main
    - release**
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  release:
    name: Deploy release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -U pip build wheel setuptools
      - name: Build distributions
        run: python -m build
      - name: Upload package as artifact to GitHub
        if: github.repository == 'projectmesa/mesa-geo' && startsWith(github.ref, 'refs/tags')
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/
      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1